---
title: "write_functions"
author: "Courtney Johnson"
date: "October 25, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
library(tidyverse)
library(rvest)
library(p8105.datasets)
library(viridis)
theme_set(theme_bw() + theme(legend.position = "bottom"))
```


## Let's write some functions

start small!

```{r}
x = rnorm(25, 5, 3)

(x - mean(x)) / sd(x)
```


Write a function to compute z scores for a vector.

```{r}
z_scores = function(x) {
  
  (x - mean(x)) / sd(x)
  
}
```


Check to see if this works...

```{r}
unif_sample = runif(100)

z_scores(unif_sample)
```

Check the following examples


```{r, error = TRUE}
z_scores(3)
z_scores("my name is Jeff")
z_scores(iris)
z_scores(sample(c(TRUE, FALSE), 25, replace = TRUE))
```

Put in some checks on inputs

```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  (x - mean(x)) / sd(x)
}
```

Check again...
```{r, error = TRUE}
z_scores(3)
z_scores("my name is Jeff")
z_scores(iris)
z_scores(sample(c(TRUE, FALSE), 25, replace = TRUE))
```


### Mean and standard deviation

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  tibble(
    mean_x = mean(x),
    sd_x = sd(x)
    
  )
}
```


```{r}
mean_and_sd(unif_sample)
```


### Multiple inputs with simple linear regression example

```{r}
sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

ls_fit = lm(y ~ x, data = sim_data)
  
beta0_hat = coef(ls_fit)[1]
beta1_hat = coef(ls_fit)[2]
```

